### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [ctgrahame/dasmoto#5]
Score: 16/16

Great job on this first project! Your Dasmoto project looked great on both the code and web side!

++ Successfully linked stylesheet.
++ Relative paths over absolute paths.
++ Utilization of indentations and whitespace. Proper HTML & CSS structure.
++ Accurate to design spec.
++ Proper usage of tags.
++ Proper usage of CSS selectors.

-- Avoid inline styles.
-- Whitespace/indentations could be cleaner but I'm just nit picking at this point. 👍 

Overall, amazing work! Keep it up!

**Comment by ctgrahame** [comment]
Thank you Joseph for quick review!!  very happy with the score too!! :)
